#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo 1>&2 "INTERNAL ERROR: ec=$? cmd=$BASH_COMMAND line=$LINENO"' ERR

[[ $(git rev-parse --symbolic-full-name @) == refs/heads/master ]] && {
    echo '● Changing from `master` branch to `main`'
    git checkout main
    git rebase
} || true

[[ -w ~/.home/cjs0 ]] && {      # This may not be writable in dent containers.
    chmod    go+X ../.. ..      # Others can search ~ and ~/.home/
    chmod -R go+rX .            # Others can read all of cjs0
} || true
