#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo 1>&2 "INTERNAL ERROR: ec=$? cmd=$BASH_COMMAND line=$LINENO"' ERR

[[ $(git rev-parse --symbolic-full-name @) == refs/heads/master ]] && {
    echo '● Changing from `master` branch to `main`'
    git checkout main
    git rebase
} || true

[[ -w ~/.home/cjs0 ]] && {      # This may not be writable in dent containers.
    chmod    go+X ../.. ..      # Others can search ~ and ~/.home/
    chmod -R go+rX .            # Others can read all of cjs0
} || true

#  Vim spelling dictionary
spadd=vim/spell/en.utf-8.add
[[ -L $spadd.spl ]] && rm -f ~/.vim/spell/en.utf-8.add.spl
vim -es -T dumb -c "mkspell! $spadd" -c 'quitall!' \
    || echo 1>&2 "WARNING: vim mkspell failed: $spadd"
