#!/usr/bin/env bash
#
#  dh/update - "meta-track" master from the main repo
#
#  This repo is a fork; we put our own work on the master branch in
#  it. However, we wish to include any work done on the master branch
#  in the upstream (or source) repo, which we assume is the `origin`
#  remote. Thus, we fetch from both "this repo" (the forked repo) and
#  the source of the fork, and rebase our master onto the source repo's
#  master. (This should often result in our commits vanishing if our
#  patches going upstream are accepted.)
#
git fetch --all
branch=$(git rev-parse --symbolic-full-name @)
[[ $branch = refs/heads/master ]] && git rebase origin/master
